import { Component, OnInit } from '@angular/core';
import { PlanService } from '@app/services/plan.service';

@Component({
  selector: 'app-tooltip',
  templateUrl: './tooltip.component.html',
  styleUrls: ['./tooltip.component.css']
})
export class TooltipComponent implements OnInit {

  private title: string;
  private text: string;

  constructor(private planService: PlanService) {
    this.title = "I'm a tooltip.";
    this.text = "This is some text that doesn't have to say anything, I just want it to fill up the screen so I can get an idea of how its going to look.";
  }

  ngOnInit() {
    this.planService.tooltipSubject.subscribe(value => {
      if (value) {
        this.title = value.id;
        switch (value.id) {
          case 'Scenario Selector':
            this.displayScenarioText();
            break;
          case 'Layer Toggles':
            this.displayLayerToggleText();
            break;
          case 'Year Selector':
            this.displayYearSelectorText();
            break;
          case 'Generation Chart':
            this.displayGenerationChartText();
            break;
          case 'Capacity Chart':
            this.displayCapacityChartText();
            break;
            case 'Renewable Energy Console':
            this.displayConsoleText();
            break;
            case 'Mini Map':
              this.displayMiniMapText();
              break;
        }
      }
    });

  }

  private displayMiniMapText() {
    this.text = "The Mini Map shows a copy of the data being displayed on the the large map display.";
  }

  private displayConsoleText() {
    this.text = "Each bar around the circle represents a year between 2016 and 2045.  The segments of the bars represent the percent of renewable energy generated by a specifc type of energy for that year.  You can tap on a bar to go directly to that year.";
  }

  private displayGenerationChartText() {
    this.text = "This chart displays the percentage of energy generated by type for the selected year.";
  }

  private displayCapacityChartText() {
    this.text = "This chart shows the capacity necessary to achieve the 2045, 100% renewable energy goal according to the selected scenario.  The dashed line shows the currently selected year.";
  }
  private displayScenarioText(): void {
    this.text = "Tap a scenario to select it.\nEach Scenario represents a plan to achieve 100% renewable energy by 2045.";
  }

  private displayLayerToggleText(): void {
    this.text = "Press and hold an icon to activate or deactivate a layer.\n Tap a layer to load information about it.";
  }

  private displayYearSelectorText(): void {
    this.text = "Touch and drag the years to select a different year.  The charts and many layers will change based on the selected year.";
  }

}
